config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w[dog cat bunny]

  validates :address, :last_seen_at, :species, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show; end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      # what happens here?
      redirect_to pet_path(@pet)
    else
      render :new, status: 422
    end
  end

  def edit; end

  def update
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private
    def pet_params
      params.require(:pet).permit(:address, :last_seen_at, :species, :image_url)
    end

    def set_pet
      @pet = Pet.find(params[:id])
    end
end


# def link_to(path, options={})
  
# end

# def pet_path(params={})
  
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets999</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="mt-5 w-50 mx-auto">
  <%= simple_form_for pet do |f| %>
    <%= f.input :address %>
    <%= f.input :last_seen_at %>
    <%= f.input :species, collection: Pet::SPECIES, prompt: "Select the species", as: :select %>
    <%= f.input :image_url %>
    <%= f.button :submit, class: 'btn-primary mt-4' %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<h2 class="mt-5">Editing pet</h2>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<div class="d-flex justify-content-between">
  <h1>LOST PETS</h1>
  <%= link_to 'I found a pet!', new_pet_path %>
</div>

<div class="mt-4 row gap-3 mx-auto">
  <% @pets.each do |pet| %>
    <%#= link_to 'Hello', pet_path(pet) %>
    <%= link_to pet_path(pet), class: "card", style: "width: 18rem;" do %>

      <%= image_tag pet.image_url %>
      <div class="card-body">
        <p><%= pet.species %></p>
        <p>
          Last seen at:<br>
          <%= pet.address %><br>
          <%= time_ago_in_words(pet.last_seen_at) %> ago
        </p>
      </div>

    <% end %>
  <% end %>
</div>

app/views/pets/new.html.erb
<h2 class="mt-5">Add a new pet</h2>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1>Pets#show</h1>
<p>Find me in app/views/pets/show.html.erb</p>

<div class="w-50">
  <%= image_tag @pet.image_url, class: "img-fluid" %>
</div>

<div class="mt-4">
  <p>A <%= @pet.species %> was found at:</p>
  <p><%= @pet.address %> <%= time_ago_in_words(@pet.last_seen_at) %> ago.</p>
</div>

<div class="mt-4">
  <%= link_to 'Contact us for more information!' ,'#' %>
</div>

<div class="mt-4 d-flex gap-3">
  <%= link_to '← Back', pets_path %>
  <%= link_to 'Edit', edit_pet_path(@pet) %>
  <%= link_to 'Delete', pet_path(@pet), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>